---
name: BlackBird
creator: Dmitry Khrykin
license: gpl-3.0
screenshotUrl: https://central.owlplug.com/products/khrykin/blackbird/0.1.0/blackbird.png
description: |- 
  Analog-inspired software synth with its own voice.

  Two 3-waveform unison oscillators
  Low-pass filter
  Single envelope for velocity, filter cutoff, and resonance
  Built-in Reverb
  Wheel modulation
pageUrl: https://khrykin.github.io/BlackBird/
type: instrument
stage: beta
tags:
- Synth
- Analog
bundles:
- name: Release Win64
  targets:
  - win64
  format: vst3
  downloadUrl: https://central.owlplug.com/products/khrykin/blackbird/0.1.0/blackbird-vst3-win64.zip
  downloadSha256: 04402c1cdcba81d82094b9860d727fd60606532d37286a0445923b0a26729c4f
  fileSize: 1730000
