---
name: Roth-AIR
creator: Daniel Rothmann
license: gpl-3.0
screenshotUrl: https://central.owlplug.com/products/rothair/rothair.png
description: |- 
  Roth-AIR is a mixing tool for easily adding airy, crispy presence to your audio. 
  
  This is achieved by a combination of multiband compression and gentle
  saturation of the highs. It enables for a stronger, more consistent presence of
  high frequency material and works particularly well with vocals, synths and strings.
  
  The process is made easy by a simple user interface, automatic makeup gain and a combined
  function 'AIR' knob.
  
  Roth-AIR is available for free in 32-bit and 64-bit as
  VST and AU (OS X only) plugins for Windows and Mac.
pageUrl: https://www.danielrothmann.com/
type: effect
tags:
- Compressor
- Mastering
bundles:
- name: Win32 VST
  targets:
  - win-x32
  formats:
  - vst
  downloadUrl: https://central.owlplug.com/products/rothair/bundles/rothair-vst-win32.zip
  downloadSha256: 29dfca9cbdc7a176aa755966a317e17605ef96de28643d0c0927497098d2a718
  fileSize: 2704000
- name: Win64 VST
  targets:
  - win-x64
  formats:
  - vst
  downloadUrl: https://central.owlplug.com/products/rothair/bundles/rothair-vst-win64.zip
  downloadSha256: f16449ef5c869d992500d8e00bb767cbe53ed3f921503a2cd94aea50d4dd4462
  fileSize: 2981000
- name: MacOs VST
  targets:
  - mac
  formats: 
  - vst
  downloadUrl: https://central.owlplug.com/products/rothair/bundles/rothair-vst-osx.zip
  downloadSha256: 5b288334cc47297a6fc6ffdd004e2ff91640560773e7166f65ff4f8ff28a3ae7
  fileSize: 2957000
