---
name: PAPU
creator: Socalabs
license: gpl-2.0
screenshotUrl: https://central.owlplug.com/products/socalabs/PAPU/papu.png
description: |
  Emulates hardware of Nintendo Gameboy
  2 Square wave channels
  Sweeps on first square wave channel
  1 Noise channel
  Waveform display
  Stereo output
  Free / Open Source
  Windows VST 32/64
  Mac VST/AU 32/64
pageUrl: https://socalabs.com/synths/papu/
type: instrument
tags:
- Synth
bundles:
- name: Win32/64 VST
  targets:
  - win32
  - win64
  format: vst
  downloadUrl: https://central.owlplug.com/products/socalabs/PAPU/bundles/PAPU-vst-win.zip
  downloadSha256: bb1869a56bff272fa90c4d3d673db11ce520d05b85660f3951e0eb5fb931b883
  fileSize: 7511000
- name: OSX VST
  targets:
  - osx
  format: vst
  downloadUrl: https://central.owlplug.com/products/socalabs/PAPU/bundles/PAPU-vst-osx.zip
  downloadSha256: 1999cbb572e133ae99eb103d1c7ba69a98ccb6c6a087e1f7fd6a37200ffc747d
  fileSize: 2101000
