---
name: SN76489
creator: Socalabs
license: lgpl-2.1
screenshotUrl: https://central.owlplug.com/products/socalabs/SN76489/sn76489.png
description: |
  Emulates Texas Instruments SN76489 of the Sega Master System and other consoles
  3 Square wave channels
  3 Note polyphony
  1 Noise channel with 2 types
  Waveform display
  Free / Open Source
  Windows VST 32/64
  Mac VST/AU 32/64
pageUrl: https://socalabs.com/synths/sn76489/
type: instrument
tags:
- Synth
bundles:
- name: Win32/64 VST
  targets:
  - win32
  - win64
  format: vst
  downloadUrl: https://central.owlplug.com/products/socalabs/SN76489/bundles/SN76489-vst-win.zip
  downloadSha256: 9c4ac6cf9aa768944fdcc7dc2899bf6fe4638e01cd8a3d16fbcc4a1c7e9f5076
  fileSize: 7509000
- name: OSX VST
  targets:
  - osx
  format: vst
  downloadUrl: https://central.owlplug.com/products/socalabs/SN76489/bundles/SN76489-vst-osx.zip
  downloadSha256: 647808ceb98029badd8b6ed87df098b064d4d1a0754970f7fa7a23a4ea8bf04d
  fileSize: 2085000
