---
name: Aether
creator: Dougal Stewart
license: mit
screenshotUrl: https://github.com/Dougal-s/Aether/raw/master/screenshot.png
description: An algorithmic reverb LV2 based on Cloudseed
pageUrl: https://dougal-s.github.io/Aether/
type: effect
tags:
- Effect
- Reverb
bundles:
- name: Release Linux64
  targets:
  - linux64
  formats:
  -lv2
  downloadUrl: https://github.com/Dougal-s/Aether/releases/download/v1.2.1/Aether-v1.2.1-Linux.tar.xz
  downloadSha256: 01d196a1b611062b3219ea3a994b54c70b379bbf6e5b15e2197c863907434dd6
  fileSize: 415000
