---
name: Dragonfly Reverb
creator: Michael Willis
license: gpl-3.0
screenshotUrl: https://central.owlplug.com/products/dragonflyreverb/dragonflyreverb.png
description: Dragonfly Reverb is a bundle of free audio effect plugins for Linux,
  MacOS, and Windows.
pageUrl: https://michaelwillis.github.io/dragonfly-reverb/
donateUrl: https://michaelwillis.github.io/dragonfly-reverb/donations.html
type: effect
tags:
- Reverb
bundles:
- name: Win32 Plugins
  targets:
  - win32
  format: various
  downloadUrl: https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.7/dragonfly-reverb-win32-3.2.7.zip
  downloadSha256: 27cfd66fe026d0c98c1754560e4b44b78e8395ef45790c544e03f18f92747952
  fileSize: 15000000
- name: Win64 Plugins
  targets:
  - win64
  format: various
  downloadUrl: https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.7/dragonfly-reverb-win64-3.2.7.zip
  downloadSha256: e8aeb6dbedee7fc70007b99ccb2ed365bfbf1f83e69f3ea3e6d06261b11568a3
  fileSize: 17000000
- name: macOS Plugins
  targets:
  - osx
  format: various
  downloadUrl: https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.7/dragonfly-reverb-mac-universal-3.2.7.zip
  downloadSha256: 5e22bbab93ae8361deacb65af38697433124e51f0172e885f7f158f0576a7f69
  fileSize: 17600000
- name: Linux x86x64 Plugins
  targets:
  - linux32
  - linux64
  format: various
  downloadUrl: https://github.com/michaelwillis/dragonfly-reverb/releases/download/3.2.7/dragonfly-reverb-linux-x86_64-3.2.7.zip
  downloadSha256: 281a82304a67dfdfe811493dd550842265749705e0b84a9cf16c4cae4730fea9
  fileSize: 15600000
