---
name: Wobbleizer
creator: Dropsnorz
license: mit
screenshotUrl: https://central.owlplug.com/products/com.dropsnorz.wobbleizer/wobbleizer.png
description: A frequency filter with LFO modulation
pageUrl: https://github.com/dropsnorz/wobbleizer
technicalUid: '2003788408'
type: effect
stage: beta
tags:
- Filter
- LFO
bundles:
- name: Wobx Win32/64
  targets:
  - win-x32
  - win-x64
  formats:
  - vst
  downloadUrl: https://central.owlplug.com/products/com.dropsnorz.wobbleizer/bundles/wobbleizer-vst-win32win64.zip
  downloadSha256: 35f9446c4494e055938ebe46df60af5162949936416816582cc738a809ab5ccd
  fileSize: 2858000
- name: Wobx Osx
  targets:
  - mac
  formats:
  - vst
  downloadUrl: https://central.owlplug.com/products/com.dropsnorz.wobbleizer/bundles/wobbleizer-vst-osx.zip
  downloadSha256: 17b98b8eda7271f16ec82571bed34ab45192621c98fcada217cde7c54bddb793
  fileSize: 3169000
