name: "Pull Request Triage"
on:
- pull_request_target

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
